services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-1
    ports:
      - "3001:3001"
    env_file:
      - .env  # Ensures Docker loads the .env file
    environment:
      MYSQL_HOST: "${HOST}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_REDIRECT_URI: "${GOOGLE_REDIRECT_URI}"
      SECRET: "${SECRET}"
      NODE_ENV: production
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-1
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://server:3001
      NODE_ENV: production
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge